const swaggerAutogen = require('swagger-autogen')();

const outputFile = './backend/swagger_output.json';
const endpointsFiles = ['./backend/controllers/endpoints']; // Array of your endpoints files

const doc = {
  info: {
    title: 'Your API',
    version: '1.0.0',
    description: 'API documentation generated by Swagger',
  },
  host: 'localhost:4000', // Update with your host and port
  basePath: '/api/v1',
  schemes: ['http'], // Add 'https' if your API is served over HTTPS
};

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
  require('./app'); // Start your server here
});
