const swaggerAutogen = require("swagger-autogen")();
const path = require("path");

const outputFile = "./swagger_output.json";
const endpointsFiles = [path.join(__dirname, "../routes/endpoints")]; // Array of your endpoints files

const doc = {
  info: {
    title: "eBlej APIs",
    version: "1.0.0",
    description: "API documentation generated by Swagger",
  },
  host: "localhost:4000",
  basePath: "/api/v1",
  schemes: ["http"],
};

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
  const swaggerDoc = require(outputFile);
  addTagsToPaths(swaggerDoc);
  require("../app");
});

function addTagsToPaths(swaggerDoc) {
  const tags = getTagForEndpoint();
  for (const path in swaggerDoc.paths) {
    const endpoint = swaggerDoc.paths[path];
    for (const method in endpoint) {
      const operation = endpoint[method];
      for (const tag of tags) {
        if (path.startsWith(`/${tag}`)) {
          operation.tags = [tag.charAt(0).toUpperCase() + tag.slice(1)];
          require("fs").writeFileSync(
            "backend/utils/swagger_output.json",
            JSON.stringify(swaggerDoc, null, 2)
          );
        }
      }
    }
  }
}

function getTagForEndpoint() {
  const swaggerDoc = require(outputFile);
  const endpoints = Object.keys(swaggerDoc.paths);
  const uniqueEndponts = Array.from(
    new Set(endpoints.map((endpoint) => endpoint.split("/")[1]))
  );
  return uniqueEndponts;
}
