const swaggerAutogen = require("swagger-autogen")();

const outputFile = "./swagger_output.json";
const endpointsFiles = ["../routes/endpoints"]; // Array of your endpoints files

const doc = {
  info: {
    title: "eBlej APIs",
    version: "1.0.0",
    description: "API documentation generated by Swagger",
  },
  host: "localhost:4000",
  basePath: "/api/v1",
  schemes: ["http"],
};

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
  require("../app");
});
