export const GET_ALL_AFFILIATES_SUCCESS = "GET_ALL_AFFILIATES_SUCCESS";
export const GET_ALL_AFFILIATES_FAIL = "GET_ALL_AFFILIATES_FAIL";
export const CREATE_AFFILIATE_SUCCESS = "CREATE_AFFILIATE_SUCCESS";
export const CREATE_AFFILIATE_FAIL = "CREATE_AFFILIATE_FAIL";
export const DELETE_AFFILIATE_SUCCESS = "DELETE_AFFILIATE_SUCCESS";
export const DELETE_AFFILIATE_FAIL = "DELETE_AFFILIATE_FAIL";
