export const NEW_SELLER_REQUEST = "NEW_SELLER_REQUEST";
export const NEW_SELLER_SUCCESS = "NEW_SELLER_SUCCESS";
export const NEW_SELLER_RESET = "NEW_SELLER_RESET";
export const NEW_SELLER_FAIL = "NEW_SELLER_FAIL";

export const GET_SELLERS_REQUEST = "GET_SELLERS_REQUEST";
export const GET_SELLERS_SUCCESS = "GET_SELLERS_SUCCESS";
export const GET_SELLERS_FAIL = "GET_SELLERS_FAIL";

export const DELETE_SELLER_REQUEST = "DELETE_SELLER_REQUEST";
export const DELETE_SELLER_SUCCESS = "DELETE_SELLER_SUCCESS";
export const DELETE_SELLER_RESET = "DELETE_SELLER_RESET";
export const DELETE_SELLER_FAIL = "DELETE_SELLER_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";